source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"
source "$GAME_DIR/.gamestate"

if [ "$DOUBLEDOORS_VISITED" = "false" ]; then
clear
typewriter_regular ""
typewriter_regular "    Together Jill and Barry passed through the double doors"
typewriter_regular "    and entered a long, extravagant dining room. The storm"
typewriter_regular "    picked up outside. The air smelled.. of..."
typewriter_regular ""
typewriter_regular "        Barry: What? What is this? . . .Blood?"
typewriter_regular "          . . .Hope this is not Chris's blood..."
typewriter_regular ""
typewriter_regular "    Jill stood behind Barry who squatted down examining the"
typewriter_regular "    puddle of blood in front of him."
typewriter_regular ""
typewriter_regular "    A man crawled out from under the large dining table."
typewriter_regular "    The man stood, and raised his arms, covered in blood,"
typewriter_regular "    and groaned approaching Jill and Barry."
typewriter_regular ""
typewriter_regular "        Barry: Hey, you, stop!"
typewriter_regular ""
typewriter_regular "    The man didn't listen, only limped closer."
typewriter_regular "    His eyes completely cloudy, as if he were already dead."
typewriter_regular "    Behind him, Jill pointed to a body partially under the"
typewriter_regular "    table. . ."
typewriter_regular ""
typewriter_regular "    It was Kenneth, from S.T.A.R.S. Bravo Team. . ."
typewriter_regular "    his throat ripped out."
typewriter_regular ""
typewriter_regular "        Barry: He's insane!"
typewriter_regular ""
typewriter_regular "    Barry fired his Colt .45."
typewriter_regular "    The man . . . er, Zombie took one more step forward."
typewriter_regular "    Then their head popped like a balloon."
typewriter_regular ""
typewriter_regular "        Barry: What the hell?"
typewriter_regular ""
typewriter_regular "        Jill: Let's report this to Wesker!"
typewriter_regular "            How do we get back to that directory though?"
typewriter_regular ""
typewriter_regular "        Barry: you can always cat ./Barry_Help1.txt"
typewriter_regular ""
typewriter_regular "          HINT: some directories will have more then one"
typewriter_regular "          Help_Barry.txt, others will show up in time!"
typewriter_regular "          use command ls frequently!"
typewriter_regular ""
sed -i 's/DOUBLEDOORS_VISITED=false/DOUBLEDOORS_VISITED=true/' "$GAME_DIR/.gamestate"
fi
