source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"
source "$GAME_DIR/.Game_Files/Design/typewriter_dramatic.sh"

clear
sleep 0.3
typewriter_dramatic ""
typewriter_dramatic "  They have escaped into the mansion, where they"
typewriter_dramatic "  thought it was safe . . ."
typewriter_dramatic ""
typewriter_dramatic "                        Yet . . ."
sleep 0.5
typewriter_regular ""
typewriter_regular "    Wesker: Wow, what a mansion!"
typewriter_regular ""
typewriter_regular "  They stood on a lush red rug that went from the large"
typewriter_regular "  front doors all the way up the grand staircase. Marble"
typewriter_regular "  floors caught bright flashes of thunder outside, booming"
typewriter_regular "  all around them in the large main hall."
typewriter_regular ""
typewriter_regular "    Jill: Captain Wesker, where's Chris?"
typewriter_regular "    Wesker: Stop it! Don't open that door!"
typewriter_regular "    Jill: But Chris is--"
typewriter_regular ""
typewriter_regular "  ...might be out there, Jill was saying but a gun went off"
typewriter_regular "  somewhere in the mansion, to the left, behind some"
typewriter_regular "  DoubleDoors."
typewriter_regular ""
typewriter_regular "    Barry: What is it?"
typewriter_regular "    Wesker: Maybe it's... Chris... Jill! Can you go?"
typewriter_regular ""
typewriter_regular "    Barry: I'm going with you."
typewriter_regular "        Chris is our old partner, ya know."
typewriter_regular ""
typewriter_regular "    Wesker: Stay alert!"
typewriter_regular ""
typewriter_regular "  Jill was relieved Barry was coming with her."
typewriter_regular "  And that he was bringing his Colt .45 with him."
typewriter_regular ""
typewriter_regular "    Barry: Remember those commands that got us in here?"
typewriter_regular "      Use them to change our directory to doubledoors"
typewriter_regular ""

sed -i 's/ENTER_MANSION_COMPLETE=false/ENTER_MANSION_COMPLETE=true/' "$GAME_DIR/.gamestate"
