source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"
sed -i 's/SEARCH_WESKER_PLAYED=false/SEARCH_WESKER_PLAYED=true/' "$GAME_DIR/.gamestate"

clear
typewriter_regular ""
typewriter_regular "    Thunder roared again outside, heavy rain beat down on the"
typewriter_regular "    large windows that filled the. . . empty Main Hall."
typewriter_regular ""
typewriter_regular "        Barry: Wesker! Help me look for him, Jill."
typewriter_regular ""
typewriter_regular "    . . . . ."
typewriter_regular ""
typewriter_regular "        Barry: Find anything, Jill?"
typewriter_regular "        Jill: Nothing. What is this all about? I can't"
typewriter_regular "          figure it out at all."
typewriter_regular "        Barry: Beats me, too."
typewriter_regular "        Jill: Now it's Wesker's time to disappear! I don't"
typewriter_regular "          know what's going on."
typewriter_regular "        Barry: Let's search for him together."
typewriter_regular "           Maybe check doubledoors again."
typewriter_regular ""
