source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"

typewriter_regular ""
typewriter_regular "    The cell was filled with silence."
typewriter_regular ""
typewriter_regular "    Jill stepped inside. Empty. Just a chair, a desk, a"
typewriter_regular "    thin layer of... webs? Something shifted above her."
typewriter_regular ""
typewriter_regular "    She looked up. Eight eyes looked back."
typewriter_regular ""
typewriter_regular "    Legs the length of her arms wrapped around"
typewriter_regular "    her shoulders, her waist, her throat. The fangs found"
typewriter_regular "    the soft place under her jaw."
typewriter_regular ""
typewriter_regular "    Her body went limp, Barry raised his gun to aim"
typewriter_regular "    but the Spider shot him with... acid? Jill could not"
typewriter_regular "    move, couldn't process, only watch in horror as Barry"
typewriter_regular "    melted where he stood."
typewriter_regular ""
typewriter_regular "    Knowing she was next."
typewriter_regular ""

source "$GAME_DIR/.Game_Files/Scenes/death.sh"
