source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"

typewriter_regular ""
typewriter_regular "        Chris: Oh Jill! Barry!"
typewriter_regular "        Jill: Oh Chris! So you're okay!"
typewriter_regular "        Chris: Yeah! You too! What happened to Wesker?"
typewriter_regular ""
typewriter_regular "    [Overhead: THE SELF-DESTRUCT SYSTEM HAS BEEN ACTIVATED.]"
typewriter_regular "    [Overhead: ALL PERSONNEL MUST EVACUATE IMMEDIATELY.]"
typewriter_regular ""
typewriter_regular "        Jill: Let's talk about it later."
typewriter_regular "        Barry: Let's get out of here!"
typewriter_regular ""

sed -i 's/CHRIS_RESCUED=false/CHRIS_RESCUED=true/' "$GAME_DIR/.gamestate"
