source "$GAME_DIR/.Game_Files/Design/typewriter_regular.sh"

typewriter_regular ""
typewriter_regular "    The cell was filled with something that shouldn't exist."
typewriter_regular ""
typewriter_regular "    Green scales. Yellow eyes that tracked Jill before she"
typewriter_regular "    could finish turning the handle. It leapt into the air."
typewriter_regular ""
typewriter_regular "    The claws came down in a single clean arc. Jill didn't have"
typewriter_regular "    time to react. She didn't have time to scream."
typewriter_regular ""
typewriter_regular "    Her head hit the floor before her body did."
typewriter_regular ""

source "$GAME_DIR/.Game_Files/Scenes/death.sh"
