#!/bin/bash

source "$GAME_DIR/lib/typewriter_regular.sh"

clear
typewriter_regular ""
typewriter_regular "    Jill read the name of the directory, Cultivation_Room, on the"
typewriter_regular "    blast door. Entering the password, the blast door lifted up."
typewriter_regular ""
typewriter_regular "    Somewhere inside, someone was typing on a keyboard."
typewriter_regular ""
typewriter_regular "    Jill and Barry stepped inside. The blast door locked behind them."
typewriter_regular "    The air was cold, and a thin fog collected around their boots."
typewriter_regular "    Jill took a step forward, watching her wonky reflection move in"
typewriter_regular "    all the large foggy glass tubes that filled the room."
typewriter_regular "    Through them, she saw him."
typewriter_regular ""
typewriter_regular "        Jill: Wesker?"
typewriter_regular ""
typewriter_regular "        Wesker: Well, well..."
typewriter_regular ""
typewriter_regular "    Wesker didn't even turn around to look at them. Just kept"
typewriter_regular "    typing on the keyboard."
typewriter_regular ""
typewriter_regular "        Barry: Cut the crap, Wesker."
typewriter_regular "          We read the orders.txt..."
typewriter_regular ""
typewriter_regular "        Jill: Why do you have to destroy S.T.A.R.S.?"
typewriter_regular ""
typewriter_regular "        Wesker: That's Umbrella's intention. This laboratory has been"
typewriter_regular "          engaging in dangerous experiments, and recently, an"
typewriter_regular "          accident occurred. A virus got out. Anyway, this disaster"
typewriter_regular "          cannot be made public."
typewriter_regular ""
typewriter_regular "        Jill: Is that why having S.T.A.R.S. nosing about is so"
typewriter_regular "          inconvenient? You're a slave to Umbrella, along with"
typewriter_regular "          these virus monsters."
typewriter_regular ""
typewriter_regular "        Wesker: I think you misunderstand me, Jill. I'm going to"
typewriter_regular "          burn this entire laboratory. If you helped create one"
typewriter_regular "          of the most powerful biological weapons. . ."
typewriter_regular "          what would you do?"
typewriter_regular ""
typewriter_regular "        Jill: You must stop this now."
typewriter_regular ""
typewriter_regular "        Wesker: Hmph. Idiots, no one understands its real value."
typewriter_regular ""
typewriter_regular "        Jill: So you're going to steal all the research?"
typewriter_regular ""
typewriter_regular "       Wesker: Better yet. I'm going to show you the Tyrant."
typewriter_regular ""
typewriter_regular "    Wesker stopped typing on the keyboard. To his left, one of the"
typewriter_regular "    large tubes started to drain. An ungodly creation inside."
typewriter_regular "    Over 8 feet tall, with a giant mutated claw as its left hand,"
typewriter_regular "    and a giant beating heart exposed on the chest."
typewriter_regular ""
typewriter_regular "    The Tyrant opened its eyes."
typewriter_regular ""
typewriter_regular "        Wesker: The Tyrant is the most powerful biological weapon"
typewriter_regular "          in the entire world. All this power will be mine. . ."
typewriter_regular ""
typewriter_regular "    In one swift motion, the Tyrant broke through the glass with"
typewriter_regular "    its mutated hand."
typewriter_regular ""
typewriter_regular "        Wesker: What? Don't come this way!"
typewriter_regular ""
typewriter_regular "    In one second, the Tyrant was out of the test tube and lifting"
typewriter_regular "    Wesker to his feet. The next, the mutated claw pierced through"
typewriter_regular "    his chest."
typewriter_regular ""
typewriter_regular "        Barry: Jill..."
typewriter_regular ""
typewriter_regular "    Barry placed a hand on Jill. Slowly encouraging her to step back"
typewriter_regular "    quietly before... The Tyrant turned, seeing them. Nowhere to run."
typewriter_regular ""
typewriter_regular "    The Tyrant threw Wesker's body across the room into a panel of"
typewriter_regular "    computer devices. Then the towering monster bared its oversized"
typewriter_regular "    teeth at them."
typewriter_regular ""
typewriter_regular "        Jill: Barry, fire!"
typewriter_regular ""
typewriter_regular "    Both S.T.A.R.S. members aimed, and fired everything into the"
typewriter_regular "    Tyrant's exposed beating heart. Barry's Colt .45 knocked the"
typewriter_regular "    Tyrant off its feet."
typewriter_regular ""
typewriter_regular "          [Overhead: THIS FACILITY WILL DETONATE. ALL DOORS ARE NOW UNLOCKED.]"
typewriter_regular "    		[Overhead: ALL PERSONNEL MUST EVACUATE IMMEDIATELY...]"
typewriter_regular ""
typewriter_regular "    Around them, emergency lights flashed. A loud siren blared on repeat."
typewriter_regular ""
typewriter_regular "        Barry: Jill we have to escape!"
typewriter_regular ""

# cultivation room logic
sed -i 's/CULTIVATION_COMPLETE=false/CULTIVATION_COMPLETE=true/' "$GAME_DIR/.gamestate"
