source "$GAME_DIR/.Game_Files/Design/typewriter_dramatic.sh"

clear
typewriter_dramatic ""
typewriter_dramatic "    THE TYRANT SLASHED IT'S GIANT CLAW DOWN,"
typewriter_dramatic "    KNOCKING THE rocket_launcher FROM JILL'S HANDS."
typewriter_dramatic "    SHE STUMBLED BACK, FALLING TO THE GROUND."
typewriter_dramatic ""
typewriter_dramatic "    BARRY DIVED FOR THE rocket_launcher AND WENT TO FIRE"
typewriter_dramatic "    BUT THE TYRANT WAS TOO FAST, SMACKING IT FROM HIS HANDS,"
typewriter_dramatic "    AND INTO THE WHIRLING BLADES OF THE HELICOPTER."
typewriter_dramatic ""
typewriter_dramatic "    EVERYTHING, INCLUDING BRAD, CAME CRASHING DOWN IN A BLAZE OVER JILL AND BARRY."
typewriter_dramatic "    SHE WATCHED AS THE TYRANT LEAPT INTO THE AIR AWAY FROM THE EMERGENCY_HELIPAD."
typewriter_dramatic "    TOWARDS. . . RACCOON_CITY. . ."
typewriter_dramatic ""
typewriter_dramatic "    IN HER FINAL MOMENTS, JILL HEARD THE SELF DESTRUCTION SEQUENCE."
typewriter_dramatic ""
typewriter_dramatic "    SELF DESTRUCTION WILL DETONATE IN. . ."
typewriter_dramatic "      ... three ..."
typewriter_dramatic "        ... two ..."
typewriter_dramatic "          ... o"
typewriter_dramatic ""

source "$GAME_DIR/.Game_Files/Scenes/End-Game/bad/Encourage_try_again.sh"
