#!/bin/bash

GAME_DIR="$HOME/RE-Linux-Easy_Basics"
source "$GAME_DIR/lib/typewriter_regular.sh"

clear
typewriter_regular ""
typewriter_regular "    The elevator doors opened with a pressurized hiss."
typewriter_regular ""
typewriter_regular "    Jill stepped out first. The floor was wet. Not from a leak —"
typewriter_regular "    the whole corridor was damp, like something lived down here."
typewriter_regular "    The lights above flickered and buzzed, casting everything in"
typewriter_regular "    a pale, sickly yellow. The walls had dark streaks running"
typewriter_regular "    down them that Jill chose not to think too hard about."
typewriter_regular ""
typewriter_regular "    Barry stepped out behind her, hand already on his Colt .45."
typewriter_regular ""
typewriter_regular "        Barry: Where are we?"
typewriter_regular ""
typewriter_regular "        Jill: An Umbrella Laboratory?"
typewriter_regular ""
typewriter_regular "        Barry: That huge pharmaceutical corporation?"
typewriter_regular "          What were they doing down here?"
typewriter_regular ""
typewriter_regular "        Jill: Creating those monsters..."
typewriter_regular ""
typewriter_regular "        Barry: Let's look around."
typewriter_regular ""
